---
name: On Push

on:
    push:
        branches:
            - main
            - test/**
            
    pull_request:
        branches:
            - main
            - test/**
        
defaults:
  run:
    shell: bash
        
jobs:
    hello-world:
        name: Say Hello From onPush
        runs-on: ubuntu-latest
        
        steps:
            - name: Echo hello
              run: echo "Hello world from onpush"
              
            - name: get git diff
              run: >
                printf "\n\nmethod 1\n\n"
                git diff --name-only
                printf "\n\nmethod 2\n\n"
                git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
                printf "\n\nmethod 3\n\n"
                # GH API: https://docs.github.com/en/rest/reference/pulls#list-pull-requests-files
                echo "git sha: ${{ github.sha }}"
              
#             - name: Trigger deployment in GitHub Actions Spike repo
#               if: contains(github.ref, 'main')
#               run: |
#                   curl -X POST https://api.github.com/repos/cpoll/github-actions-test/dispatches \
#                   -H "Accept: application/vnd.github.v3+json" \
#                   -u ${{ env.ACTIONS_PAT }} \
#                   --data '{"event_type": "event1"}'
            
