---
name: On Push

on:
    push:
        branches:
            - main
            - test/**
            
    pull_request:
        branches:
            - main
            - test/**
        
defaults:
  run:
    shell: bash
        
jobs:
    hello-world:
        name: Say Hello From onPush
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              
            - name: Run hello.sh
              run: ./hello.sh
            
            - name: Echo hello
              run: echo "Hello world from onpush"
              
            - name: get git diff
              run: |
                printf "\n\nmethod 1\n\n"
                m1=$(git diff --name-only)
                echo $m1
                printf "\n\nmethod 2\n\n"
                m2=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
                echo $m2
                printf "\n\nmethod 3\n\n"
                git diff --name-only ${{ github.event.before }}..${{ github.event.after }}
                printf "\n\nmethod 3\n\n"
                git diff --name-only ${{ github.event.before }}..${{ github.event.after }}
                printf "\n\nmethod 4\n\n"
                git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
                printf "\n\nmethod 5\n\n"
                git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }}..${{ github.sha }}
                # GH API: https://docs.github.com/en/rest/reference/pulls#list-pull-requests-files
                
                
                echo "git sha: ${{ github.sha }}"
                echo "git before/after: ${{ github.event.before }}..${{ github.event.after }}"
              
#             - name: Trigger deployment in GitHub Actions Spike repo
#               if: contains(github.ref, 'main')
#               run: |
#                   curl -X POST https://api.github.com/repos/cpoll/github-actions-test/dispatches \
#                   -H "Accept: application/vnd.github.v3+json" \
#                   -u ${{ env.ACTIONS_PAT }} \
#                   --data '{"event_type": "event1"}'
            
