---
name: On Push

on:
    push:
        branches:
            - main
            - test*
        
defaults:
  run:
    shell: bash
        
jobs:
    hello-world:
        name: Say Hello From onPush
        runs-on: ubuntu-latest
        
        steps:
            - name: Echo hello
              run: echo "Hello world from onpush on test-push-source branch"
              
#             - name: Trigger deployment in GitHub Actions Spike repo
#               if: contains(github.ref, 'main')
#               run: |
#                   curl -X POST https://api.github.com/repos/cpoll/github-actions-test/dispatches \
#                   -H "Accept: application/vnd.github.v3+json" \
#                   -u ${{ env.ACTIONS_PAT }} \
#                   --data '{"event_type": "event1"}'
            
